<?php

define("USE_ROUTER",TURE);

define("GOOGLE_API_KEY_LIVE","AIzaSyAEQGBGMylr3LVa7msZKaGCp3j0SD4X2fQ");

define("STP_DISTANCE_WEIGHT",7);
define("STP_DURATION_WEIGHT",3);

define("TOKEN_ERROR_WAYPOINT_MAX",'WAYPOINT_MAX');
define("TOKEN_ERROR_WAYPOINT_MIN",'WAYPOINT_MIN');
define("TOKEN_ERROR_WAYPOINT_FORMAT_ERROR",'WAYPOINT_FORMAT_ERROR');
define("TOKEN_ERROR_NO_INPUT",'NO_INPUT');

define("STATUS_IN_PROGRESS",'in progress');
define("STATUS_FAILURE",'failure');
define("STATUS_SUCCESS",'success');

define("ROUTE_ERROR_NO_ROUTE_PROVIDED",'NO_ROUTE_PROVIDED');
define("ROUTE_ERROR_TOKEN_NOT_EXIST",'TOKEN_NOT_EXIST');
